<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Connection\DB_Connection_Read.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.RDS" Version="4.0.21.6" />
    <PackageReference Include="Npgsql" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\fraud_poc_project_buss\fraud_poc_project_buss.csproj" />
    <ProjectReference Include="..\fraud_poc_project_models\fraud_poc_project_models.csproj" />
  </ItemGroup>
</Project>
