<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <RestorePackagesPath>../src/nuget-packages</RestorePackagesPath>
    </PropertyGroup>
    
    <ItemGroup>
        <Compile Remove="Connection\DB_Connection_Read.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.RDS" Version="4.0.21.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
        <PackageReference Include="Npgsql" Version="8.0.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\fraud_poc_project_buss\fraud_poc_project_buss.csproj" />
        <ProjectReference Include="..\fraud_poc_project_models\fraud_poc_project_models.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Newtonsoft.Json">
        <HintPath>..\src\nuget-packages\newtonsoft.json\13.0.4\lib\net6.0\Newtonsoft.Json.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>
