services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        dll: "docke_web_Api.dll"
    image: docke_web_api
    container_name: docke_web_api:offline
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ASPNETCORE_ENVIRONMENT: "LOC"  # "Production"
    expose:
      - "8080"
    networks:
      - edge
    logging: 
        driver: json-file
        options:
            max-size: "10m"
            max-file: "5"


  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - api    # simplified, no health condition
    ports:
      - "8085:8085" # this says that docker-compose port 8085 maps to nginx port 8085 of the server property
    volumes:
      - ./nginx.conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - edge
    logging: 
        driver: json-file
        options:
            max-size: "10m"
            max-file: "5"

networks:
  edge:
    driver: bridge