<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <DocumentationFile>C:\Development\Therron\training\src\fraud_poc_project.xml</DocumentationFile>
        <UserSecretsId>ff8b7950-3516-4b83-9e03-9af24f59945e</UserSecretsId>
    </PropertyGroup>

    <PropertyGroup>
        <RestorePackagesPath>../src/nuget-packages</RestorePackagesPath>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Fraud\Dto\**" />
      <Compile Remove="Fraud\Mapping\**" />
      <Compile Remove="Fraud\Models\**" />
      <Compile Remove="Fraud\Repository\**" />
      <Compile Remove="Fraud\Rules\**" />
      <Content Remove="Fraud\Dto\**" />
      <Content Remove="Fraud\Mapping\**" />
      <Content Remove="Fraud\Models\**" />
      <Content Remove="Fraud\Repository\**" />
      <Content Remove="Fraud\Rules\**" />
      <EmbeddedResource Remove="Fraud\Dto\**" />
      <EmbeddedResource Remove="Fraud\Mapping\**" />
      <EmbeddedResource Remove="Fraud\Models\**" />
      <EmbeddedResource Remove="Fraud\Repository\**" />
      <EmbeddedResource Remove="Fraud\Rules\**" />
      <None Remove="Fraud\Dto\**" />
      <None Remove="Fraud\Mapping\**" />
      <None Remove="Fraud\Models\**" />
      <None Remove="Fraud\Repository\**" />
      <None Remove="Fraud\Rules\**" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="tmpConn_strings.json" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="CapitecRootCA.cer" />
      <None Remove="CapitecRootCA.crt" />
      <None Remove="CapitecRootCA.pem" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.3.32" />
      <PackageReference Include="AWSSDK.SecretsManager" Version="4.0.4.16" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
      <PackageReference Include="Microsoft.OpenApi" Version="1.6.14" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
      <PackageReference Include="Serilog" Version="3.1.1" />
      <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
      <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
      <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.6.2" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.6.2" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.6.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\fraud_poc_project_repo\fraud_poc_project_repo.csproj" />
      <ProjectReference Include="..\Kafka\Credit.Kafka.Messaging\Credit.Kafka.Messaging.csproj" />
    </ItemGroup>
</Project>
