<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeSymbols>true</IncludeSymbols>
        <IncludeSource>true</IncludeSource>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <Description>Credit Domain event messaging with Kafka in dotnet</Description>
        <RepositoryUrl>https://github.com/capitecbankltd/credit-shared_lib-kafka-messaging</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <VersionPrefix>1.2.3</VersionPrefix>
    </PropertyGroup>

    <PropertyGroup>
        <RestorePackagesPath>../src/nuget-packages</RestorePackagesPath>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AWS.MSK.Auth" Version="1.0.0" />
      <PackageReference Include="Confluent.Kafka" Version="2.14.2" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Credit.Kafka.Messaging.Contracts\Credit.Kafka.Messaging.Contracts.csproj" />
    </ItemGroup>
</Project>