{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tester-api.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "tester-api.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.ingress.className "nginx" }}
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.ingress.nginx.proxyBodySize }}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.ingress.nginx.proxyConnectTimeout }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.ingress.nginx.proxySendTimeout }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.ingress.nginx.proxyReadTimeout }}"
    nginx.ingress.kubernetes.io/proxy-http-version: "{{ .Values.ingress.nginx.proxyHTTPVersion }}"
    {{- else if eq .Values.ingress.className "traefik" }}
    traefik.ingress.kubernetes.io/router.entrypoints: "{{ .Values.ingress.traefik.entrypoints }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tester-api.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
{{- end }}
``