apiVersion: v1
kind: Service
metadata:
  name: {{ include "tester-api.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "tester-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "tester-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP