<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeSymbols>true</IncludeSymbols>
        <IncludeSource>true</IncludeSource>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <VersionPrefix>1.0.1</VersionPrefix>
        <Description>Domain event contracts</Description>
        <RepositoryUrl>https://github.com/capitecbankltd/credit-shared_lib-kafka-messaging</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <PropertyGroup>
        <RestorePackagesPath>../src/nuget-packages</RestorePackagesPath>
    </PropertyGroup>

</Project>
