name: CI - Docker + Helm Validation

on:
  pull_request:
    branches: [ "main" ]

  push:
    branches: [ "main", "Docker", "K8s" ]

env:
  IMAGE_NAME: docke_web_api
  IMAGE_TAG: ci
  CHART_PATH: charts/docke-web-api
  NAMESPACE: docke-web-api

jobs:
  ci-pr:
    if: github.event_name == 'pull_request'
    name: PR Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: CI validation
        run: echo "Run PR checks here"

  ci-main:
    if: github.event_name == 'push'
    name: Branch CI Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: CI validation
        run: echo "Run branch CI checks here"