apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "docke-web-api.fullname" . }}-pvc
  namespace: {{ .Values.namespace.name | default "docke-web-api" }}
  labels:
    {{- include "docke-web-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi