{{- if and .Values.persistence.enabled (not .Values.persistence.perReplica) (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "docke-web-api.fullname" . }}-pvc
  namespace: {{ .Values.namespace.name | default "docke-web-api" }}
  labels:
    {{- include "docke-web-api.labels" . | nindent 4 }}
spec:
  accessModes: {{ toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
{{- end }}
